pipeline{
    agent any
    stages{
        stage('build'){
            steps{
                sh 'echo "this is build stages"'
            }
        }
        stage('test'){
            steps{
                sh 'echo "this is test stage"'
            }
        }
        stage('deploy'){
            steps{
                sh 'echo "this deploy satge"'
            }
        }
        stage('post'){
            steps{
                sh 'echo "this is post stage"'
            }
        }
    }
}